package tool.wu.heng.ui.theme;

/* compiled from: Type.kt */
@kotlin.Metadata(d1 = {"\u0000\n\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0011\u0010\u0000\u001a\u00020\u0001¢\u0006\b\n\u0000\u001a\u0004\b\u0002\u0010\u0003¨\u0006\u0004"}, d2 = {"Typography", "Landroidx/compose/material3/Typography;", "getTypography", "()Landroidx/compose/material3/Typography;", "app_release"}, k = 2, mv = {1, 9, 0}, xi = 48)
/* loaded from: /workspace/.recovery/dex/classes3.dex */
public final class TypeKt {
    private static final androidx.compose.material3.Typography Typography;

    public static final androidx.compose.material3.Typography getTypography() {
        return Typography;
    }

    static {
        androidx.compose.ui.text.font.FontFamily fontFamily = androidx.compose.ui.text.font.FontFamily.Companion.getDefault();
        androidx.compose.ui.text.font.FontWeight normal = androidx.compose.ui.text.font.FontWeight.Companion.getNormal();
        androidx.compose.ui.text.font.FontFamily fontFamily2 = fontFamily;
        androidx.compose.ui.text.TextStyle textStyle = new androidx.compose.ui.text.TextStyle(0L, androidx.compose.ui.unit.TextUnitKt.getSp(16), normal, (androidx.compose.ui.text.font.FontStyle) null, (androidx.compose.ui.text.font.FontSynthesis) null, fontFamily2, (java.lang.String) null, androidx.compose.ui.unit.TextUnitKt.getSp(0.5d), (androidx.compose.ui.text.style.BaselineShift) null, (androidx.compose.ui.text.style.TextGeometricTransform) null, (androidx.compose.ui.text.intl.LocaleList) null, 0L, (androidx.compose.ui.text.style.TextDecoration) null, (androidx.compose.ui.graphics.Shadow) null, (androidx.compose.ui.graphics.drawscope.DrawStyle) null, 0, 0, androidx.compose.ui.unit.TextUnitKt.getSp(24), (androidx.compose.ui.text.style.TextIndent) null, (androidx.compose.ui.text.PlatformTextStyle) null, (androidx.compose.ui.text.style.LineHeightStyle) null, 0, 0, (androidx.compose.ui.text.style.TextMotion) null, 16645977, (kotlin.jvm.internal.DefaultConstructorMarker) null);
        androidx.compose.ui.text.font.FontFamily fontFamily3 = androidx.compose.ui.text.font.FontFamily.Companion.getDefault();
        androidx.compose.ui.text.font.FontWeight normal2 = androidx.compose.ui.text.font.FontWeight.Companion.getNormal();
        androidx.compose.ui.text.font.FontFamily fontFamily4 = fontFamily3;
        androidx.compose.ui.text.TextStyle textStyle2 = new androidx.compose.ui.text.TextStyle(0L, androidx.compose.ui.unit.TextUnitKt.getSp(22), normal2, (androidx.compose.ui.text.font.FontStyle) null, (androidx.compose.ui.text.font.FontSynthesis) null, fontFamily4, (java.lang.String) null, androidx.compose.ui.unit.TextUnitKt.getSp(0), (androidx.compose.ui.text.style.BaselineShift) null, (androidx.compose.ui.text.style.TextGeometricTransform) null, (androidx.compose.ui.text.intl.LocaleList) null, 0L, (androidx.compose.ui.text.style.TextDecoration) null, (androidx.compose.ui.graphics.Shadow) null, (androidx.compose.ui.graphics.drawscope.DrawStyle) null, 0, 0, androidx.compose.ui.unit.TextUnitKt.getSp(28), (androidx.compose.ui.text.style.TextIndent) null, (androidx.compose.ui.text.PlatformTextStyle) null, (androidx.compose.ui.text.style.LineHeightStyle) null, 0, 0, (androidx.compose.ui.text.style.TextMotion) null, 16645977, (kotlin.jvm.internal.DefaultConstructorMarker) null);
        androidx.compose.ui.text.font.FontFamily fontFamily5 = androidx.compose.ui.text.font.FontFamily.Companion.getDefault();
        androidx.compose.ui.text.font.FontWeight medium = androidx.compose.ui.text.font.FontWeight.Companion.getMedium();
        androidx.compose.ui.text.font.FontFamily fontFamily6 = fontFamily5;
        androidx.compose.ui.text.TextStyle textStyle3 = new androidx.compose.ui.text.TextStyle(0L, androidx.compose.ui.unit.TextUnitKt.getSp(16), medium, (androidx.compose.ui.text.font.FontStyle) null, (androidx.compose.ui.text.font.FontSynthesis) null, fontFamily6, (java.lang.String) null, androidx.compose.ui.unit.TextUnitKt.getSp(0.15d), (androidx.compose.ui.text.style.BaselineShift) null, (androidx.compose.ui.text.style.TextGeometricTransform) null, (androidx.compose.ui.text.intl.LocaleList) null, 0L, (androidx.compose.ui.text.style.TextDecoration) null, (androidx.compose.ui.graphics.Shadow) null, (androidx.compose.ui.graphics.drawscope.DrawStyle) null, 0, 0, androidx.compose.ui.unit.TextUnitKt.getSp(24), (androidx.compose.ui.text.style.TextIndent) null, (androidx.compose.ui.text.PlatformTextStyle) null, (androidx.compose.ui.text.style.LineHeightStyle) null, 0, 0, (androidx.compose.ui.text.style.TextMotion) null, 16645977, (kotlin.jvm.internal.DefaultConstructorMarker) null);
        androidx.compose.ui.text.font.FontFamily fontFamily7 = androidx.compose.ui.text.font.FontFamily.Companion.getDefault();
        androidx.compose.ui.text.font.FontWeight medium2 = androidx.compose.ui.text.font.FontWeight.Companion.getMedium();
        androidx.compose.ui.text.font.FontFamily fontFamily8 = fontFamily7;
        Typography = new androidx.compose.material3.Typography((androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, textStyle2, textStyle3, (androidx.compose.ui.text.TextStyle) null, textStyle, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, (androidx.compose.ui.text.TextStyle) null, new androidx.compose.ui.text.TextStyle(0L, androidx.compose.ui.unit.TextUnitKt.getSp(11), medium2, (androidx.compose.ui.text.font.FontStyle) null, (androidx.compose.ui.text.font.FontSynthesis) null, fontFamily8, (java.lang.String) null, androidx.compose.ui.unit.TextUnitKt.getSp(0.5d), (androidx.compose.ui.text.style.BaselineShift) null, (androidx.compose.ui.text.style.TextGeometricTransform) null, (androidx.compose.ui.text.intl.LocaleList) null, 0L, (androidx.compose.ui.text.style.TextDecoration) null, (androidx.compose.ui.graphics.Shadow) null, (androidx.compose.ui.graphics.drawscope.DrawStyle) null, 0, 0, androidx.compose.ui.unit.TextUnitKt.getSp(16), (androidx.compose.ui.text.style.TextIndent) null, (androidx.compose.ui.text.PlatformTextStyle) null, (androidx.compose.ui.text.style.LineHeightStyle) null, 0, 0, (androidx.compose.ui.text.style.TextMotion) null, 16645977, (kotlin.jvm.internal.DefaultConstructorMarker) null), 15679, (kotlin.jvm.internal.DefaultConstructorMarker) null);
    }
}
